---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - client/assets/native/**/*.js
  - client/src/**/*.js
  - server/**/*.js
  - routes/**/*.js
  - client/assets/native/**/*.css
  - client/src/**/*.css
  - server/**/*.css
  - routes/**/*.css
exclude_paths:
- dist/**/*
- node_modules/**/*
- client/bower_components/**/*